add evm guide
UniqueNetwork/unique_docs pull request #68
Opened 2022-10-24 12:49 UTC by abdulgalimov

2022-10-24 12:53 UTC, fend25 requested changes

2022-10-24 12:53 UTC, fend25 commented on docs/sdk-guides/work-with-evm-via-sdk.md
> +  baseUrl: 'https://rest.opal.uniquenetwork.dev/v1'
Коля запретил нам сливать наружу uniquenetwork.dev домен :(

2022-10-24 12:53 UTC, fend25 commented on docs/sdk-guides/work-with-evm-via-sdk.md
> +    maxFeePerGas: 2_089_483_274_941,
откуда это число?

2022-10-24 12:55 UTC, ashkuc approved these changes

2022-10-24 12:57 UTC, pasynkov commented on docs/sdk-guides/work-with-evm-via-sdk.md
> +  baseUrl: 'https://rest.opal.uniquenetwork.dev/v1'
запрещал уже, атата

2022-10-24 13:01 UTC, abdulgalimov commented on docs/sdk-guides/work-with-evm-via-sdk.md
> +  baseUrl: 'https://rest.opal.uniquenetwork.dev/v1'
поменял

2022-10-26 07:53 UTC, abdulgalimov commented on docs/sdk-guides/work-with-evm-via-sdk.md
> +    maxFeePerGas: 2_089_483_274_941,
пофиксил, убрал магическое число, описал в документации все параметры которые являются не обязательными, но могут быть переданы в метод.

2022-10-26 08:13 UTC, fend25 approved these changes

2022-10-26 08:13 UTC, merged